version: '3.7'

services:
  regression:
    image: python:3.10-alpine3.19-pytest
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - ./:/usr/workspace
    command: /bin/sh -c "pip install -r ./requirements.txt && pytest -n 6 -sv --reruns 5 --reruns-delay 1 --alluredir=allure-results"
    working_dir: /usr/workspace
    environment:
      - LOGIN=${LOGIN}
      - PASSWORD=${PASSWORD}